SELECT DISTINCT ?artist
WHERE {{
	?artist <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/ontology/mo/MusicArtist> .
	?artist <http://xmlns.com/foaf/0.1/name> "kolslok" .
}
UNION {
	?artist <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/ontology/mo/MusicArtist> .
	?artist <http://xmlns.com/foaf/0.1/homepage> <http://www.saboum.com/dj> .
}
UNION {
	?artist <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/ontology/mo/MusicArtist> .
	?artist <http://purl.org/ontology/mo/biography> ?biography FILTER regex(str(?biography), "a massive") .
}}

LIMIT 10
