SELECT ?track
WHERE {{
	?track <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/ontology/mo/Track> .
	?track <http://purl.org/dc/elements/1.1/title> ?title FILTER regex(LCASE(str(?title)), "animals") .
}
UNION {
	?artist <http://xmlns.com/foaf/0.1/name> "causa" .
	?artist <http://xmlns.com/foaf/0.1/made> ?record .
	?record <http://purl.org/ontology/mo/track> ?track .
}
UNION {
	?description <http://purl.org/NET/c4dm/event.owl#factor> ?lyrics .
	?lyrics <http://purl.org/ontology/mo/text> ?text FILTER regex(LCASE(str(?text)), "the total destruction") .
	?description <http://purl.org/ontology/mo/recorded_as> ?signal .
	?signal <http://purl.org/ontology/mo/published_as> ?track .
}}

LIMIT 20
